openapi: 3.0.4
info:
  title: API de Alumnos
  description: |
    Plantilla base OpenAPI 3.0 para exponer un recurso tipo "alumno".
    Llena los campos de esta plantilla con la información de tu API.
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /api/alumno:
    post:
      tags:
        - alumno
      summary: Crear un nuevo alumno
      description: Agrega un nuevo alumno al sistema.
      operationId: crearAlumno
      requestBody:
        description: Objeto alumno a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlumnoReqBody'
      responses:
        '201':
          description: Alumno creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlumnoResError'
        default:
          description: Error inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - alumno
      summary: Trae la lista de alumnos
      description: Trae la lista de alumnos registrados en el sistema.
      operationId: getAlumnoList
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Pagina de la lista de elementos, cada pagina es de 10
      responses:
        '200':
          description: Lista de alumnos del sistema OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alumno'
  /api/alumno/{id}:
    # get:
    #   summary: Traer un alumno por id
    #   description: Traer el detalle de un alumno registrado en el sistema.
    #   operationId: getAlumnoById
    #   tags:
    #     - alumno
    #   parameters:
    #     - in: path
    #       name: id
    #       schema:
    #         type: integer
    #       required: true
    #       description: Numeric ID of the user to get
    #   responses:
    #     '200':
    #       description: alumno del sistema OK
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Alumno'
    #     '404':
    #       description: No se encontro el alumno
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Error'
    delete:
      summary: Eliminar un alumno por id
      description: Eliminar un alumno registrado en el sistema.
      operationId: deleteAlumnoById
      tags:
        - alumno
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: alumno del sistema OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Alumno eliminado
        '404':
          description: No se encontro el alumno
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: No se encontro el alumno
omponents:
  schemas:
    AlumnoResError:
      type: object
      required:
        - msg
        - status
      properties:
        msg:
          type: string
          example: El campo 'nombre' es requerido
        status:
          type: string
          example: ERROR
    AlumnoReqBody:
      type: object
      required:
        - nombre
        - grupo
      properties:
        nombre:
          type: string
          example: Juan Pérez
        grupo:
          type: string
          example: "5A"
        apellido:
          type: string
          example: "Hdz"
    Alumno:
      type: object
      required:
        - nombre
        - matricula
        - grupo
        - created_at
      properties:
        nombre:
          type: string
          example: Juan Pérez
        matricula:
          type: integer
          example: 20231234
        grupo:
          type: string
          example: "5A"
        created_at:
          type: string
          format: date-time
          example: "2025-07-05T00:57:48Z"
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
